# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
import sys
from pathlib import Path
from itertools import product

template = """
# This Dockerfile is auto-generated by generate-dockerfiles.py
FROM quay.io/pypa/{prefix}_{version_id}_{arch}

ENV HDF5_VERSION=1.14.6
ENV HDF5_DIR=/usr/local

COPY install_libaec.sh /tmp/install_libaec.sh
RUN bash /tmp/install_libaec.sh
COPY install_hdf5.sh /tmp/install_hdf5.sh
RUN bash /tmp/install_hdf5.sh
"""

ROOT = Path(__file__).parent

BASE_IMAGE_IDS = [
    ("manylinux", "2_28"),
    ("musllinux", "1_2"),
]
ARCHS = ["x86_64", "aarch64"]


def main(argv: list[str] | None = None) -> int:
    output_dir = ROOT / "Dockerfiles"
    output_dir.mkdir(exist_ok=True)
    for (prefix, version_id), arch in product(BASE_IMAGE_IDS, ARCHS):
        stem = f"{prefix}_{version_id}_{arch}"
        output_dir.joinpath(stem).write_text(
            template.format(
                prefix=prefix,
                version_id=version_id,
                arch=arch,
            )
        )


if __name__ == "__main__":
    sys.exit(main())
